### ISSUE TITLE
Cleaning up BIDS examples that showcase use of physiological and other continuous recordings

### ISSUE THREAD

**Issue by melanieganz** [bids-standard/bids-examples#186]
Dear @bids-maintenance and @robertoostenveld ,

we are finalizing the BIDS PET examples and we are using the physiological and other continuous recordings as inspiration (https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/06-physiological-and-other-continuous-recordings.html) to handle the blood data. 
Now we noticed that the examples that are uploaded that use the _physio.tsv are e.g. missing the associated _physio.json. I get that this is not required, but optional, but I can't seem to find an example where this file is present. 

Can we maybe add this to one of the examples?

Cheers,
Mel

**Comment by sappelhoff** [comment]
@melanieganz apologies for the late reply. Can you tell us which datasets you had in mind to add `physio.json` files?

>  get that this is not required, but optional,

that actually makes me wonder ... I thought that `physio.json` files MUST be supplied if `physio.tsv.gz` is present. Mainly because in `physio.tsv.gz` files, there are no header columns ... these must be supplied in the JSON

--> and without the JSON, nobody knows what's in the columns.



Sounds like something we should clarify and potentially also update the validator.
