### ISSUE TITLE
ds116 issue with some events files

### ISSUE THREAD

**Issue by rwblair** [bids-standard/bids-examples#397]
The last two lines of most of the task-auditoryoddballwithbuttonresponsetotargetstimuli events.tsv has the value "standard" in the column for response_time. Not sure what these trailing lines are for.

https://github.com/bids-standard/bids-examples/blob/master/ds116/sub-02/func/sub-02_task-auditoryoddballwithbuttonresponsetotargetstimuli_run-02_events.tsv#L149

**Comment by effigies** [comment]
TBH this looks like a bad bidsification, but you'd need someone who understands openfmri to figure out what went wrong. https://legacy.openfmri.org/s3-browser/?prefix=ds000116/ds000116_R1.0.0/uncompressed/

@jmumford Is this something you could decipher?

**Comment by Remi-Gau** [comment]
actually there are also other lines in the middle of the tsv with n/a for durations for those standard events

**Comment by Remi-Gau** [comment]
looks like the numeric values on the last 3 rows are the same as the onsets on the 3 first ones: I'd be OK just removing them (any other issues in this dataset?) and maybe commenting on the openneuro dataset that seems to have the issue too

**Comment by effigies** [comment]
Short term, let's make the examples look sensible. If this is somehow valid, someone can explain it to me and we can adjust the schema and/or validator.

**Comment by jmumford** [comment]
I'm not sure how the openfmri data were converted to make the openneuro data, but the openfmri event.tsv counterpart (behavdata.txt) seems okay and I'm noticing a few things (and combining with Remi's comments to have it in one spot).

- Based on the openfmri data the response times should be occurring each time stimulus = target.  The response times all seem to be n/a in the openneuro data, so that wasn't carried over correctly
- Remi is correct that the onsets of the last 3 lines match the first 3 _but_ I wouldn't just remove them because the first 3 lines also seem corrupt as they're missing the stimulus information.
- Just to reiterate, Remi is correct that durations in the middle are sometimes n/a.  I'm not sure why that occurs.  It occurs for a mix of Stimulus=target and Stimulus=standard trial_types
- In the openneuro events.tsv files, the durations for the Stimulus=target trials appear to be the RTs (it would be better if they were in a response_time column)

@effigies, what are the examples you're referring to that you need to look sensible?  I can figure out how to recreate the events.tsv files correctly from the behavdata.txt files in the openfmri data, but I'm not sure if that's what you're trying to do here.

**Comment by Remi-Gau** [comment]
#399 would at least remove the weird lines at the end of each file

**Comment by effigies** [comment]
@jmumford The thing Ross linked: https://github.com/bids-standard/bids-examples/blob/master/ds116/sub-02/func/sub-02_task-auditoryoddballwithbuttonresponsetotargetstimuli_run-02_events.tsv?plain=1
